---
- hosts: all
  become: true
  pre_tasks:
  - name: update Debian (apt)
    tags: always
    apt:
      update_cache: yes
      upgrade: dist
    when: ansible_distribution == "Debian"
  - name: update Rocky (dnf)
    tags: always, update
    dnf:
      update_only: yes
      update_cache: yes
    when: ansible_distribution == "Rocky"
- hosts: webservers
  become: true
  tasks:
  - name: install apache and php packages
    tags: apache, apache2, debian
    package:
      name:
        - "{{ apache_package }}"
        - "{{ php_package }}"
      state: latest
  - name: copy default html
    tags: apache, apache2, httpd
    copy:
      src: default_site.html
      dest: /var/www/html/index.html
      owner: root
      group: root
      mode: 0644
- hosts: db_servers
  become: true
  tasks:
  - name: install maria db
    tags: apache, rhel, rocky, db
    package:
      name: mariadb
      state: latest
