---
- hosts: all
  become: true
  pre_tasks:
  - name: update Debian (apt)
    apt:
      update_cache: yes
      upgrade: dist
    when: ansible_distribution == "Debian"
  - name: update Rocky (dnf)
    dnf:
      update_only: yes
      update_cache: yes
    when: ansible_distribution == "Rocky"
- hosts: webservers
  become: true
  tasks:
  - name: install apache and php packages
    package:
      name:
        - "{{ apache_package }}"
        - "{{ php_package }}"
      state: latest
- hosts: db_servers
  become: true
  tasks: 
  - name: install maria db
    package:
      name: mariadb
      state: latest
