version: "3"
services:
  giropops-senhas:
    image: linuxtips/giropops-senhas:1.0
    ports:
      - 5000:5000
    environment:
      REDIS_HOST: redis
  redis:
    image: redis
    ports:
      - 6379:6379
#networks:
 # drivers: bridge
