apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: giropops
    service: webserver
  name: giropops
spec:
  containers:
  - image: nginx
    name: webserver
    volumeMounts: 
    - mountPath: /giropops # where to mount inside the volume
      name: first-emptydir  
    resources: 
        limits:
          cpu: "1" # max
          memory: "128Mi"
        requests:
          cpu: "0.5" # min/standard
          memory: "64Mi"
  dnsPolicy: ClusterFirst
  restartPolicy: Always
  volumes: 
  - name: first-emptydir
    emptyDir: 
      sizeLimit: 256Mi
