# generate local file
resource "local_file" "test" {
    filename = "./directorycreated/test.txt"
    content =  "this is a content generated by terraform"
    #directory_permission =  "0777"
    #file_permission =  "0777"
}